gitSourceBranch = "main"
changelog = true

# navbar
[[navbar.items]]
href = "https://discord.gg/Qm3JNyEc32"
label = "Discord"
position = "right"

# api docs ordering
[[classOrder]]
classes = ["Iris", "State"]

[[classOrder]]
section = "Widgets"
classes = [
	"Window",
	"Menu",
	"Format",
	"Text",
	"Basic",
	"Tree",
    "Tab",
    "Image",
	"Input",
	"Drag",
	"Slider",
	"Combo",
	"Plot",
	"Table",
]

[[classOrder]]
classes = ["Internal"]

[docusaurus]
onBrokenMarkdownLinks = "warn"
trailingSlash = false
[docusarus.themeConfig.prism]
additionalLangues = ["lua", "luau", "cpp"]

[footer]
style = "dark"
copyright = "Â©2024 Michael_48 & SirMallard"
