[package]
name = "sirmallard/iris"
description = "Iris is an Immediate-Mode GUI Library for Roblox, based on Dear ImGui, designed for creating debug, visualisation and content-creation tool UI."
version = "2.4.1"

license = "MIT"
authors = ["Michael-48", "SirMallard"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["default.project.json", "lib", "lib/**", "LICENSE.txt", "wally.toml"]
private = false
