[package]
name = "michael-48/Iris"
description = "Iris is an Immediate mode GUI Library for Roblox, Based on Dear ImGui."
version = "2.1.5"

license = "MIT"
authors = ["Michael-48", "SirMallard"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["default.project.json", "lib", "lib/**", "LICENSE.txt", "wally.toml"]
private = false