[package]
name = "michael-48/iris"
description = "Iris is an Immediate mode GUI Library for Roblox, Based on Dear ImGui."
version = "2.1.1"

license = "MIT"
authors = ["Michael-48", "SirMallard"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src/client/Iris", "src/client/Iris/*", "model.project.json", "wally.toml"]
private = false

[dependencies]

[server-dependencies]

[dev-dependencies]
